// Generated by scripts/fantacalcio-voti-to-json.mjs: the official votes of every round on disk.
import type {VotoRow} from '@/lib/fantasy/voti';

export const VOTI: Array<{round: number; rows: VotoRow[]}> = [
];
